/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'isSystem' : IDL.Bool,
  'text' : IDL.Text,
  'isForced' : IDL.Bool,
  'isBigMessage' : IDL.Bool,
  'timestamp' : Time,
  'isBroadcast' : IDL.Bool,
  'isBot' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getMessages' : IDL.Func([Time], [IDL.Vec(ChatMessage)], ['query']),
  'postMessage' : IDL.Func([ChatMessage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'isSystem' : IDL.Bool,
    'text' : IDL.Text,
    'isForced' : IDL.Bool,
    'isBigMessage' : IDL.Bool,
    'timestamp' : Time,
    'isBroadcast' : IDL.Bool,
    'isBot' : IDL.Bool,
  });
  
  return IDL.Service({
    'getMessages' : IDL.Func([Time], [IDL.Vec(ChatMessage)], ['query']),
    'postMessage' : IDL.Func([ChatMessage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };